#!/usr/bin/env bash
# Install the PROJECT_MAP freshness check as a pre-commit hook.
#
# Usage:  bash scripts/install_hooks.sh
#
# Writes .git/hooks/pre-commit (idempotent). Uninstall:  rm .git/hooks/pre-commit
set -eu

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

if [ ! -d .git ]; then
    echo "!! Not a git repository; nothing to install." >&2
    exit 1
fi

HOOK=".git/hooks/pre-commit"

# Never clobber a hook that isn't ours.
if [ -f "$HOOK" ] && ! grep -q "check_project_map" "$HOOK" 2>/dev/null; then
    cp "$HOOK" "$HOOK.bak"
    echo "Existing hook backed up to $HOOK.bak"
fi

# Embed the real project path (same pattern as setup_termux.sh's algobot
# wrapper) so the installed hook resolves the check script no matter where
# git invokes it from.
cat > "$HOOK" <<EOF
#!/bin/sh
# PROJECT_MAP freshness check — generated by scripts/install_hooks.sh.
# Re-run that script to update; delete this file to uninstall.
# No shebang-with-env here: Termux has no /usr/bin/env, so the hook is a
# POSIX sh wrapper that explicitly invokes bash for the real check.
exec bash "$PROJECT_DIR/scripts/check_project_map.sh"
EOF
chmod +x "$HOOK"

echo "Installed pre-commit hook -> $HOOK"
echo "It blocks commits that leave PROJECT_MAP.md stale."
echo "Uninstall:  rm $HOOK"